# THIS IS USED TO CONFIGURE THE APPLICATION PROPERTIES
server:
  port: 5000

spring:
  # THESE ARE THE SPRING CONFIGURATIONS RELATED TO THE DATABASE
  datasource:
    url: jdbc:postgresql://localhost:5332/ecoles
    username: nide
    password: jesus123

  jpa:
    # THESE ARE THE JPA CONFIGURATIONS RELATED TO THE DATABASE 
    hibernate:
      # ddl-auto: create-drop # THIS WILL CREATE THE TABLES AND DROP THEM WHEN THE APPLICATION IS STOPPED
      ddl-auto: update # THIS WILL CREATE THE TABLES AND UPDATE THEM WHEN THE APPLICATION IS STOPPED
      # ddl-auto: create # THIS WILL CREATE THE TABLES AND NOT DROP THEM WHEN THE APPLICATION IS STOPPED
      # ddl-auto: validate # THIS WILL VALIDATE THE TABLES AND NOT DROP THEM WHEN THE APPLICATION IS STOPPED

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: true

main:
  # THIS IS THE MAIN CLASS OF THE APPLICATION THAT WILL BE RUN WHEN THE APPLICATION STARTS
  web-application-type: servlet