version: '3.9'

services:
  # THE SERVICES THAT WILL BE USED IN THE DOCKER-COMPOSE FILE
  db:
    # THE NAME OF THE SERVICE
    container_name: postgres # THE NAME OF THE CONTAINER
    image: postgres # THE IMAGE THAT WILL BE USED

    environment:
      # THE ENVIRONMENT VARIABLES THAT WILL BE USED
      - POSTGRES_USER=nide # THE USER THAT WILL BE USED
      - POSTGRES_PASSWORD=jesus123 # THE PASSWORD THAT WILL BE USED
      - PGDATA=/data/postgres # THE PATH WHERE THE DATA WILL BE SAVED

    volumes:
      # THE VOLUMES THAT WILL BE USED IN THE CONTAINER (THE PATHS ARE RELATIVE TO THE PROJECT)
      - db:/data/postgres # THE VOLUME THAT WILL BE USED TO SAVE THE DATA

    ports:
      # THE PORTS THAT WILL BE USED
      - "5332:5432"

    networks:
      # THE NETWORKS THAT WILL BE USED IN THE CONTAINER (THE NETWORKS MUST BE CREATED BEFORE)
      - db

    restart: unless-stopped # THE RESTART POLICY THAT WILL BE USED IN THE CONTAINER IF IT STOPS

networks:
  # THE NETWORKS THAT WILL BE USED IN THE DOCKER-COMPOSE FILE 
  db:
    driver: bridge # THE DRIVER THAT WILL BE USED IN THE NETWORK

volumes:
  # THE VOLUMES THAT WILL BE USED IN THE DOCKER-COMPOSE FILE 
  db:
